"""Issue Tracker Export — export findings as GitHub Issues or Jira tickets."""

from __future__ import annotations

import json
import logging

import httpx

from models import ScanFinding

log = logging.getLogger("proxy-engine.issue-export")


def format_github_issue(finding: dict, target: str = "") -> dict:
    """Format a finding as a GitHub Issue payload."""
    severity = finding.get("severity", "info").upper()
    name = finding.get("name", "Security Finding")
    url = finding.get("url", "")

    title = f"[{severity}] {name}"
    if len(title) > 100:
        title = title[:97] + "..."

    labels = [f"severity:{severity.lower()}", "security"]
    source = finding.get("source", "")
    if source:
        labels.append(f"source:{source}")

    body = f"""## Security Finding: {name}

**Severity:** {severity}
**URL:** {url}
**Source:** {source or 'ProxyEngine Scanner'}
**Confidence:** {finding.get('confidence', 'N/A')}

### Description
{finding.get('description', 'No description available.')}

### Evidence
```
{finding.get('raw', finding.get('evidence', 'N/A'))[:2000]}
```

### Reproduction
```bash
{finding.get('curl_command', 'N/A')}
```

### Remediation
{finding.get('remediation', 'Review and fix the identified vulnerability.')}

---
*Generated by ProxyEngine*
"""

    return {
        "title": title,
        "body": body,
        "labels": labels,
    }


def format_jira_ticket(finding: dict, project_key: str = "SEC") -> dict:
    """Format a finding as a Jira ticket payload."""
    severity = finding.get("severity", "info").lower()
    name = finding.get("name", "Security Finding")

    # Map severity to Jira priority
    priority_map = {
        "critical": "Highest",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "info": "Lowest",
    }

    description = f"""h2. {name}

*Severity:* {severity.upper()}
*URL:* {finding.get('url', '')}
*Source:* {finding.get('source', 'ProxyEngine')}
*Confidence:* {finding.get('confidence', 'N/A')}

h3. Description
{finding.get('description', 'No description.')}

h3. Evidence
{{code}}
{finding.get('raw', finding.get('evidence', 'N/A'))[:2000]}
{{code}}

h3. Reproduction
{{code:bash}}
{finding.get('curl_command', 'N/A')}
{{code}}

h3. Remediation
{finding.get('remediation', 'Review and fix.')}

----
_Generated by ProxyEngine_
"""

    return {
        "fields": {
            "project": {"key": project_key},
            "summary": f"[{severity.upper()}] {name}"[:255],
            "description": description,
            "issuetype": {"name": "Bug"},
            "priority": {"name": priority_map.get(severity, "Medium")},
            "labels": ["security", f"severity-{severity}"],
        }
    }


async def export_to_github(
    finding: dict,
    repo: str,
    token: str,
    target: str = "",
) -> dict:
    """Create a GitHub Issue from a finding.

    repo: "owner/repo" format
    token: GitHub personal access token
    """
    issue = format_github_issue(finding, target)

    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.post(
            f"https://api.github.com/repos/{repo}/issues",
            json=issue,
            headers={
                "Authorization": f"token {token}",
                "Accept": "application/vnd.github.v3+json",
            },
        )

        if resp.status_code == 201:
            data = resp.json()
            return {
                "success": True,
                "issue_url": data.get("html_url", ""),
                "issue_number": data.get("number", 0),
            }
        else:
            return {
                "success": False,
                "error": f"GitHub API error: {resp.status_code}",
                "body": resp.text[:500],
            }


async def export_to_jira(
    finding: dict,
    jira_url: str,
    email: str,
    api_token: str,
    project_key: str = "SEC",
) -> dict:
    """Create a Jira ticket from a finding.

    jira_url: e.g. "https://yourcompany.atlassian.net"
    """
    import base64

    ticket = format_jira_ticket(finding, project_key)
    auth = base64.b64encode(f"{email}:{api_token}".encode()).decode()

    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.post(
            f"{jira_url.rstrip('/')}/rest/api/2/issue",
            json=ticket,
            headers={
                "Authorization": f"Basic {auth}",
                "Content-Type": "application/json",
            },
        )

        if resp.status_code in (200, 201):
            data = resp.json()
            return {
                "success": True,
                "issue_key": data.get("key", ""),
                "issue_url": f"{jira_url}/browse/{data.get('key', '')}",
            }
        else:
            return {
                "success": False,
                "error": f"Jira API error: {resp.status_code}",
                "body": resp.text[:500],
            }


def bulk_format_github(findings: list[dict], target: str = "") -> list[dict]:
    """Format multiple findings as GitHub Issues."""
    return [format_github_issue(f, target) for f in findings]


def bulk_format_jira(findings: list[dict], project_key: str = "SEC") -> list[dict]:
    """Format multiple findings as Jira tickets."""
    return [format_jira_ticket(f, project_key) for f in findings]
